app:
  name: 'go-clean-template'
  version: '1.0.0'

http:
  port: '8080'

options:
  db: mongo

mongo:
  host: hao88.cloud
  port: 8082
  database: heji
  username: db_user
  password: HaoHejiServer0214!
  timeoutMax: 10s

jwt:
  secret: AV8DHao88.cloud1F@!9fe3=!W$W-FaF`L1L2I3I4E5W
  expirationTime: 720h


